# tasks before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (ubuntu, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation
