- name: install gcc, tmux, and tar 
  tags: gcc,tmux,ubuntu
  package:
    name: 
      - tmux 
      - gcc 
      - tar
      - git
    state: latest

- name: copy default tmux config
  tags: tmux,config
  copy:
    src: tmux_configuration.conf
    dest: /home/spektre/.tmux.conf
    owner: spektre
    group: spektre
    mode: 0644

- name: install latest neovim
  tags: neovim
  unarchive:
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /opt
    remote_src: yes
  notify: link_neovim    

- name: check .config/nvim
  find:
    paths: '/home/spektre/.config/nvim'
    file_type: any
    hidden: true
  register: nvim_config

- name: clone my neovim config
  tags: neovim
  command:
    cmd: "git clone https://github.com/Erik-Serbicki/neovim-config.git /home/spektre/.config/nvim"
  when: nvim_config.matched == 0

- name: install docker
  tags: docker
  package:
    name:
      - docker.io
      - docker-compose
    state: latest
    notify: create_docker_directory



- name: install zoxide and fzf
  tags: zoxide,fzf,terminal
  package:
    name:
      - fzf
      - zoxide

- name: initialize zoxide 
  tags: terminal,zoxide
  shell: |
    echo 'eval "$(zoxide init --cmd cd bash)"' >> /home/spektre/.bashrc
    source /home/spektre/.bashrc
  args:
    executable: /usr/bin/bash

- name: install eza
  tags: eza,terminal
  package:
    name: eza

- name: configure eza
  tags: eza,terminal
  shell: |
    echo 'alias ls="eza -lh --group-directories-first --git"' >> /home/spektre/.bashrc

- name: install uv (python)
  tags: uv,python
  shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  notify:
    - uv_autocomplete
    - uv_install_python
