- name: link_neovim
  command:
    cmd: "ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/bin/nvim"

- name: create_docker_directory
  tags: docker
  command:
    cmd: "mkdir /home/spektre/docker"


- name: initialize zoxide 
  tags: terminal,zoxide
  shell: |
    echo 'eval "$(zoxide init --cmd cd bash)"' >> /home/spektre/.bashrc
    source /home/spektre/.bashrc
  args:
    executable: /usr/bin/bash

- name: configure eza
  tags: eza,terminal
  shell: |
    echo 'alias ls="eza -lh --group-directories-first --git"' >> /home/spektre/.bashrc

- name: uv_autocomplete
  shell: |
    echo 'eval "$(uv generate-shell-completion bash)"' >> /home/spektre/.bashrc

- name: uv_install_python
  shell: |
    uv python install
